// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1L67Eqyahdb_vTLfusGuXkDGs3XoCO_w',
    appId: '1:1018886420916:web:6df2a3b07d504094061ae1',
    messagingSenderId: '1018886420916',
    projectId: 'register-c1ed6',
    authDomain: 'register-c1ed6.firebaseapp.com',
    databaseURL: 'https://register-c1ed6-default-rtdb.firebaseio.com',
    storageBucket: 'register-c1ed6.appspot.com',
    measurementId: 'G-SZ2EZH5VCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu22kuxTxBjkANLb8I-3HbutzVPeuKL3Q',
    appId: '1:1018886420916:android:a041f0a00bfedd9a061ae1',
    messagingSenderId: '1018886420916',
    projectId: 'register-c1ed6',
    databaseURL: 'https://register-c1ed6-default-rtdb.firebaseio.com',
    storageBucket: 'register-c1ed6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLw4-Tp9Gu_xgMFAU1-Xyt8_-UVlAmWr0',
    appId: '1:1018886420916:ios:72cff61ac6117b87061ae1',
    messagingSenderId: '1018886420916',
    projectId: 'register-c1ed6',
    databaseURL: 'https://register-c1ed6-default-rtdb.firebaseio.com',
    storageBucket: 'register-c1ed6.appspot.com',
    iosBundleId: 'com.example.realTime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLw4-Tp9Gu_xgMFAU1-Xyt8_-UVlAmWr0',
    appId: '1:1018886420916:ios:902137bc122b8b45061ae1',
    messagingSenderId: '1018886420916',
    projectId: 'register-c1ed6',
    databaseURL: 'https://register-c1ed6-default-rtdb.firebaseio.com',
    storageBucket: 'register-c1ed6.appspot.com',
    iosBundleId: 'com.example.realTime.RunnerTests',
  );
}
